resources:
  - name: dbp_repo
    type: GitRepo
    configuration:
      gitProvider: tsuyo_github
      path: tsuyo/jfrog-pipelines--quickstart-docker-build-and-push
      branches:
        include: master

  - name: dbp_image
    type: Image
    configuration:
      registry: artifactory
      sourceRepository: docker_local
      imageName: jfrog.tsuyo.org/docker/dbp
      imageTag: latest
      autoPull: true
      
  - name: dbp_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: artifactory
      buildName: dbp_build
      buildNumber: 1    

  - name: dbp_promoted_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: artifactory
      buildName: dbp_build
      buildNumber: 1
      

pipelines:
  - name: pipeline_dbp
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: dbp_group
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: jfrog.tsuyo.org/docker/dbp
          dockerImageTag: ${run_number}
          inputResources:
            - name: dbp_repo
          integrations:
            - name: artifactory

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: dbp_group
          targetRepository: docker-local
          integrations:
            - name: artifactory
          inputSteps:
            - name: docker_build
          outputResources:
            - name: dbp_image

      - name: publish_dbp_build
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push
          outputResources:
            - name: dbp_build_info

      - name: promote_dbp_build
        type: PromoteBuild
        configuration:
          targetRepository: docker-dev-local
          integrations:
            - name: artifactory
          inputResources:
            - name: dbp_build_info
          outputResources:
            - name: dbp_promoted_build_info
