template: true
valuesFilePath: ./values.yml

resources:
  - name: dbp_repo
    type: GitRepo
    configuration:
      gitProvider: {{ .Values.myRepo.gitProvider }}
      path: {{ .Values.myRepo.path }}
      branches:
        include: {{ .Values.myRepo.branch }}

  - name: dbp_image
    type: Image
    configuration:
      registry: {{ .Values.myArtifactory.name }}
      sourceRepository: {{ .Values.myArtifactory.pushRepo }}
      imageName: {{ .Values.docker.image.name }}
      imageTag: {{ .Values.docker.image.tag }}
      autoPull: true
      
  - name: dbp_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: {{ .Values.myArtifactory.name }}
      buildName: {{ .Values.buildInfo.name }}
      buildNumber: {{ .Values.buildInfo.number }}

  - name: dbp_promoted_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: {{ .Values.myArtifactory.name }}
      buildName: {{ .Values.buildInfo.name }}
      buildNumber: {{ .Values.buildInfo.number }}
      

pipelines:
  - name: pipeline_dbp
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: dbp_group
          dockerFileLocation: {{ .Values.docker.file.location }}
          dockerFileName: {{ .Values.docker.file.name }}
          dockerImageName: {{ .Values.docker.image.name }}
          dockerImageTag: ${run_number}
          inputResources:
            - name: dbp_repo
          integrations:
            - name: {{ .Values.myArtifactory.name }}
        execution:
          onStart:
            - echo "[TM] onStart"
            - echo ${int_artifactory_apikey} | docker login --username admin --password-stdin jfrog.tsuyo.org

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: dbp_group
          targetRepository: {{ .Values.myArtifactory.pushRepo }}
          integrations:
            - name: {{ .Values.myArtifactory.name }}
          inputSteps:
            - name: docker_build
          outputResources:
            - name: dbp_image

      - name: publish_dbp_build
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push
          outputResources:
            - name: dbp_build_info

      - name: promote_dbp_build
        type: PromoteBuild
        configuration:
          targetRepository: {{ .Values.myArtifactory.promoteRepo }}
          integrations:
            - name: {{ .Values.myArtifactory.name }}
          inputResources:
            - name: dbp_build_info
          outputResources:
            - name: dbp_promoted_build_info
