myRepo:
  gitProvider: tsuyo_github
  path: tsuyo/jfrog-pipelines--quickstart-docker-build-and-push
  branch: master
myArtifactory:
  name: artifactory
  pushRepo: docker-local
  promoteRepo: docker-dev-local
  username: admin
docker:  
  image:
    name: platform.tsuyo.org/docker/dbp
    tag: latest
  file:
    location: .
    name: Dockerfile
buildInfo:
  name: dbp_build
  number: 1
